# Generated by Django 5.2.5 on 2025-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=20)),
                ('error_code', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('log_msg', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tickets log',
            },
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Prijs van één ticket',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_nr', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('ticket_count', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('has_payed', models.CharField(max_length=1)),
                ('checked_in', models.CharField(max_length=1)),
                ('email_subscription', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
